// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.778
package userpages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/CSPF-Founder/iva/panel/views/components"
	"github.com/CSPF-Founder/iva/panel/views/helpers"
)

func Login(data helpers.BaseData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"bg-light min-vh-100 d-flex flex-column align-items-center dark:bg-transparent\"><div class=\"container d-flex flex-row flex-grow-1 align-items-center justify-content-center\"><div class=\"row justify-content-center\"><div class=\"col-lg-9\"><form action=\"/users/login\" id=\"login-form\" method=\"POST\" autocomplete=\"off\"><div class=\"card-group d-block d-md-flex row\"><div class=\"card text-white bg-primary col-md-7 p-4 mb-0\"><div class=\"card-body\"><h3>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(data.ProductTitle)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/pages/userpages/login.templ`, Line: 17, Col: 32}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(" - ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(data.Title)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/pages/userpages/login.templ`, Line: 17, Col: 49}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</h3><p class=\"\"></p><div class=\"input-group mb-3\"><span class=\"input-group-text\"><svg class=\"icon\"><use xlink:href=\"/static/vendor/@coreui/icons/svg/free.svg#cil-user\"></use></svg></span> <input type=\"text\" class=\"form-control\" name=\"username\" id=\"username\" placeholder=\"Username\" required></div><div class=\"input-group mb-3\"><span class=\"input-group-text\"><svg class=\"icon\"><use xlink:href=\"/static/vendor/@coreui/icons/svg/free.svg#cil-lock-locked\"></use></svg></span> <input type=\"password\" class=\"form-control\" name=\"password\" id=\"password\" placeholder=\"Password\" required></div><p class=\"\"></p><div class=\"row\"><div class=\"col-6\"><button form=\"login-form\" class=\"btn btn-secondary\" type=\"submit\" name=\"login\" value=\"Login\">Login</button></div><div class=\"col-6 text-end\"></div></div></div><div class=\"form-group wrapper justify-content-center mb-2\"><h5 class=\"text-warning\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		for _, item := range data.Flashes {
			var templ_7745c5c3_Var4 string
			templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(item.Message)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/pages/userpages/login.templ`, Line: 66, Col: 25}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</h5></div></div><div class=\"card col-md-5 d-flex flex-row py-5 align-items-center justify-content-center\"><div class=\"card-body text-center\"><div><img class=\"img-thumbnail img-center-100 border-0 center-block\" src=\"/external/images/secondary-logo.png\"></div></div></div></div></form></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.Footer(data.CurrentYear, data.CopyrightFooterCompany).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<script src=\"/static/vendor/@coreui/coreui-pro/js/coreui.bundle.min.js\"></script><script src=\"/static/vendor/simplebar/js/simplebar.min.js\"></script></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
